// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCC9IimIlIdbEs0I7bWLvzygUBEwzylkc',
    appId: '1:535531621961:web:bfe6a811a76e96fdd67998',
    messagingSenderId: '535531621961',
    projectId: 'flutter-todo-e1454',
    authDomain: 'flutter-todo-e1454.firebaseapp.com',
    storageBucket: 'flutter-todo-e1454.firebasestorage.app',
    measurementId: 'G-1HSHEW9BEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtVGyQ3d-idzKFRTC9O3NdwYaME4-g3zI',
    appId: '1:535531621961:android:8946bd58ed144a93d67998',
    messagingSenderId: '535531621961',
    projectId: 'flutter-todo-e1454',
    storageBucket: 'flutter-todo-e1454.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpqhf4aBvnKjfCEy73Iw3kZzGR36m3n4o',
    appId: '1:535531621961:ios:8e753417dd903d54d67998',
    messagingSenderId: '535531621961',
    projectId: 'flutter-todo-e1454',
    storageBucket: 'flutter-todo-e1454.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpqhf4aBvnKjfCEy73Iw3kZzGR36m3n4o',
    appId: '1:535531621961:ios:8e753417dd903d54d67998',
    messagingSenderId: '535531621961',
    projectId: 'flutter-todo-e1454',
    storageBucket: 'flutter-todo-e1454.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCC9IimIlIdbEs0I7bWLvzygUBEwzylkc',
    appId: '1:535531621961:web:806f25890ab44ba3d67998',
    messagingSenderId: '535531621961',
    projectId: 'flutter-todo-e1454',
    authDomain: 'flutter-todo-e1454.firebaseapp.com',
    storageBucket: 'flutter-todo-e1454.firebasestorage.app',
    measurementId: 'G-NBXC2R1MJF',
  );
}
